[project]
name = "rag-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.4.0",
    "fastapi>=0.128.0",
    "groq>=1.0.0",
    "ollama>=0.6.1",
    "ruff>=0.14.11",
    "uvicorn>=0.40.0",
]
